/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab5;

public class App {
    

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.menuLoop();
    }
}
