/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onlinefarmacy;


import java.util.Scanner;

import com.google.gson.JsonObject;

public class Main {
    public static Boolean exitprogram = false;

    public static void main(String[] args) {
        System.out.println(System.getProperty("user.dir"));
        JsonObject config = Config.loadConfig("src/main/java/com/onlinefarmacy/config.json");


        String farmacyName = config.get("farmacyName").getAsString();
        String recDirectory = config.get("receiptsDirectory").getAsString();

        System.out.println("Welcome to " + farmacyName);
        Scanner scanner = new Scanner(System.in);
        InitializeDrugs.setDrugs();
        InitializeReceipts.setReceipts();
        while (!exitprogram) {
            Menu.menu(scanner, recDirectory);
        }
        scanner.close();
    }
}

