CREATE SCHEMA `students_db`;

USE `students_db`;

CREATE TABLE students(`id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NOT NULL, `age` INT NOT NULL,  `grade` VARCHAR(45) NOT NULL, PRIMARY KEY(`id`),  UNIQUE INDEX `id_UNIQUE`(`id` ASC) VISIBLE);
