version: '3.8'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3307:3307"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["mysqld"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      my_network:
        ipv4_address: 172.16.238.10

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

