/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;


import lab4.com.eu222dq.Calculator;

public class App {
    public static void main(String[] args){

        Calculator calculator = new Calculator();
        calculator.main();   
        
        System.out.println(new App().getGreeting());
    }
    public String getGreeting() {
        return "Hello World!";
    }
}
