/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {

  private Scanner input;

  private App(Scanner scannerInput) {
    this.input = scannerInput;
  }

  /**
    * Solution to first task.
    */
  public void helloThere() {
    System.out.print("What is your name? ");
    String name = input.nextLine();
  
    HelloThere hello = new HelloThere();
    String greeting = hello.hello(name);
    System.out.println(greeting);     
  }

  /**
    * Solution for the second task.
    */
  public void seconds() {
    System.out.println("Enter hours, minutes and seconds: ");
    int hours = input.nextInt();
    int minutes = input.nextInt();
    int seconds = input.nextInt();

    Time time = new Time();
    int totalSeconds = time.toSeconds(hours, minutes, seconds);
    System.out.println("In seconds the time is: " + totalSeconds);
  }

  /**
 * Solution for the third task.
 */
  public void imInaBand() {
    Album album = new Album("Wish You Were Here", 1975, "Pink Floyd");
    System.out.print(album.getName() + "was released "); 
    System.out.println(album.getYear() + " by");
    System.out.println(album.getArtist());
  }


  /**
     * Solution for the fourth task.
     */
  public void bestAlbumsEver() {
    AlbumGenerator albumGenerator = new AlbumGenerator();
    Album[] greatestAlbums = albumGenerator.generateAlbums();
    for (Album a : greatestAlbums) {
      System.out.print(a.getName() + "was released "); 
      System.out.println(a.getYear() + " by");
      System.out.println(a.getArtist());
    }
  }

  /**
   * shows various array operations such as calculating average,
   * finding the largest value, and manipulating the array.
   */
  public void workingWithArrays() {
    int[] array = {1, 2, 5, 10, 7};
    System.out.print("Input numbers: [ ");
    for (int e : array) {
      System.out.print(" " + e);
    }
    System.out.print(" ]");
    
    ArrayAlgorithms arrayAlgorithms = new ArrayAlgorithms();
    System.out.println("\nAverage is: " + arrayAlgorithms.average(array));
    System.out.println("Largest value is: " + arrayAlgorithms.maxValue(array));
    System.out.println("Index of smallest value is: " + arrayAlgorithms.minIndex(array));

    System.out.print("Shifted array: [ ");
    for (int e : arrayAlgorithms.shift(array)) {
      System.out.print(e + " ");
    }
    System.out.print(" ]");

    System.out.print("\nShuffled: [ ");
    for (int e : arrayAlgorithms.shuffle(array)) {
      System.out.print(e + " ");
    }
    System.out.print(" ]");
        
  }

  /**
     * Starting point of the first assignment.
     *
     * @param args is not used.
     */
  public static void main(String[] args) {
    // we create a scanner object to work with
    // it is advised to create one and only one scanner for a specific stream in the whole
    // application scanners should be closed when you are done and this also closes
    // the underlying stream
    Scanner consoleInput = new Scanner(System.in, "UTF-8");

    App app = new App(consoleInput);

    // Task 1
    app.helloThere();
    System.out.println("\n");
    // Task 2
    app.seconds();
    System.out.println("\n");
    // Task 3
    app.imInaBand();
    System.out.println("\n");
    // Task 4
    app.bestAlbumsEver();
    System.out.println("\n");
    // Task 5
    app.workingWithArrays();
    System.out.println("\n");
    //  If you are going for the higher grades you can uncomment the following lines
    //  and implement the methods in the GradeC class.
    GradeC gradeC = new GradeC();
    gradeC.calculator(consoleInput);
    
    System.out.println("\n");
    gradeC.arrays2D();
    
    System.out.println("\n");
    gradeC.band();
    
    GradeA gradeA = new GradeA();
    System.out.println("\n");
    gradeA.calculator(consoleInput);
    
    System.out.println("\n");
    gradeA.genre();
    // now we are exiting the application so time to close the scanner.
    consoleInput.close();
  }
}
