/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testgreetingContainsHello() {
        App app = new App();
        String greeting = app.getGreeting();
        assertEquals("Hello World!", greeting, "Expected greeting: 'Hello World!'");
    }
}
